version: '3.1'

services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db