version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pas123
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db